server {
    listen 80;

    location / {
        proxy_pass http://nestjs:5000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    # Optionally expose metrics endpoint directly
    location /Trhdsg_gg2026_Edd5qS {
        proxy_pass http://nestjs:5000/Trhdsg_gg2026_Edd5qS;
    }
}
